name:         "Jekyll/Gulp/Sass/Foundation5.5.3/Browser-Sync"
description:  "Website boilerplate with Jekyll/Gulp/Sass/Foundation5.5.3/Browser-Sync"

# typekit_id: yourKitID

# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
# include:     ['.htaccess']
exclude:     ['node_modules', 'bower_components', 'assets', 'assets/img', 'assets/scripts', 'assets/styles', 'gulpfile.js', 'package.json', 'bower.json', 'README.md', 'Gemfile', 'Gemfile.lock', .DS_Store]
keep_files:  ['js', 'css', 'images']
# gems:        []
# timezone:    nil
# encoding:    nil

# future:      true
# show_drafts: false
# limit_posts: 0
# highlighter: pygments

# relative_permalinks: true

permalink: /:title
# paginate_path: 'page:num'
# paginate:      nil

# markdown:      kramdown
# markdown_ext:  markdown,mkdown,mkdn,mkd,md
# textile_ext:   textile

# excerpt_separator: "\n\n"

# safe:        false
# watch:       false    # deprecated
# server:      false    # deprecated
# host:        0.0.0.0
# port:        4000
# baseurl:     ""
# lsi:         false

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex
#   fenced_code_blocks: true

# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false

#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true
